name: Resourcepack Zipper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Get previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}

    - name: Get next minor version
      id: semver
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create ZIP file
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        ZIP_NAME="RP.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r "${ZIP_NAME}" .

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: resource-pack-artifact
        path: ${{ env.ZIP_NAME }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      with:
        tag_name: release-1.12
        release_name: Release 1.12
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/${{ env.ZIP_NAME }}
        asset_name: ${{ env.ZIP_NAME }}
        asset_content_type: application/zip